import Head from "next/head";
import React from "react";

const Layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title ? title + " - Swasha" : "Swasha"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/png/favicon.png" />
      </Head>
      <div className="flex justify-between min-h-screen flex-col">
        {children}
      </div>
    </>
  );
};

export default Layout;
